easy_admin:
#    site_name: 'ALIOTH <em style="font-size: 80%;">Soc.Coop.</em>'
    site_name: '<img src="/images/logo-alioth-group-ridotto.png"/>' 
    list:
        actions:
            # the 'title' content is displayed when the cursor is over the icon
            - { name: 'edit', icon: 'pencil', label: false, title: 'Modiica' }
            - { name: 'delete', icon: 'trash-alt', label: false, title: 'Elimina' }
    design:
      menu:
        - { route: 'homepage', label: 'Vai ai Feedback', icon: 'home' }
        - { entity: 'Cantieri', label: 'Cantieri', icon: 'building' }
        - { entity: 'CommentiPubblici', label: 'Feedback e segnalazioni', icon: 'comments' }
        - { entity: 'Province', label: 'Province', icon: 'map-marker' }
        - { entity: 'RegoleFatturazione', label: 'Regole di fatturazione', icon: 'wave-square' }
       
#    entities:
#        # List the entity class name you want to manage
#       - App\Entity\Cantieri
#        - App\Entity\CommentiPubblici
#        - App\Entity\Province
#       - App\Entity\RegoleFatturazione 

    formats:
      date:     'd/m/Y'
      time:     'H:i'
      datetime: 'd/m/Y H:i:s'

    entities:
      Cantieri:
            class: App\Entity\Cantieri
            # help: 'Cantieri gestiti dalla Alioth'
            list:
                title: "Elenco Cantieri"
                fields:
                    - { property: 'nameJob', label: 'Nome Cantiere' }
                    - { property: 'city', label: 'Città' }
                    - { property: 'isPublic', label: 'Accetta feedback'}
                    - { property: 'dateStartJob', type: 'date', label: 'Avvio lavoro' }
                    - { property: 'dateEndJob',  type: 'date', label: 'Fine lavoro' }
                    - { property: 'distance', label: 'Km da sede' }
                sort: 'createdAt'  
                filters:
                    - { property: 'city', label: 'Città' } 
                    - { property: 'isPublic', label: 'Accetta feedback'}
            form:
                title: "Dati di cantiere"
                fields:
                    - { type: 'group', label: 'INFORMAZIONI DI BASE', icon: 'building', columns: 6}
                    - { property: 'nameJob', label: 'Nome Cantiere' }
                    - { property: 'city', label: 'Città' }
                    - { property: 'provincia', label: 'Provincia' }
                    - { property: 'isPublic', label: 'Accetta feedback', help: 'Selezionare se vuoi che il cantiere sia visibile a tutti.'}
                    - { property: 'dateStartJob', type: 'date', label: 'Data avvio lavoro', type_options: { widget: 'single_text' }  }
                    - { property: 'dateEndJob',  type: 'date', label: 'Data fine lavoro', type_options: { widget: 'single_text' }  }
                    - { property: 'descriptionJob', label: 'Descrizione ', help: 'Descrivere brevemente il progetto di cantiere'}
                    - { property: 'maps', label: 'Coordinate geografiche', help: 'Indicare le coordinate per una geolocalizzazione'}
                    - { property: 'distance', label: 'Km da sede', format: '%04s', help: 'Distanza da sede in Km complessivi di A/R'}
                    - { type: 'group', label: 'PIANIFICAZIONE CANTIERE', icon: 'wallet', columns: 4, help: 'Inserire i dati per una corretta pianificazione'}
                    - { property: 'hourlyRate', label: 'Tariffa Oraria', format: '%5.2f', help: 'Prezzo orario di vendita in alternativa alla tariffa a corpo',  type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'flatRate', label: 'Tariffa a Corpo', format: '%10.2f', help: 'Prezzo di vendita secondo la regola del ciclo di fatturazione, in alternativa alla tariffa oraria',  type: 'money', type_options: { currency: 'EUR' }}
                    - { property: 'regolaFatturazione', label: 'Ciclo di fatturazione',  help: 'Si applica alla tariffa a corpo o alla tariffa oraria sul monte ore consuntivo'}
                    - { property: 'isPlanningPerson', label: 'Usa pianificazione del Personale', help: 'Se non scelto il lavoro è a consuntivo'}
                    - { property: 'planningHours', label: 'Ore previste', help: 'Indicare le ore pianificate per ciclo di fatturazione'}
                    - { property: 'isPlanningMaterial', label: 'Usa pianificazione dei materiali', help: 'Se non scelto i materiali sono forniti dal committente'}
                    - { property: 'planningCostMaterial', label: 'Costo materiali previsti', type: 'money', type_options: { currency: 'EUR' }, help: 'Indicare il costo dei materiali previsti per la completa fornitura di tutto il periodo del progetto'}
                    - { type: 'section', label: 'INFORMAZIONI RECORD', icon: 'database', columns: 4 }
                    - { property: 'id', label: '#Id Cantiere', type_options: { disabled: true } }
                    - { property: 'createdAt', label: 'Data ultimo aggiornamento', type: datetime, type_options: { disabled: true } }

      CommentiPubblici:
            class: App\Entity\CommentiPubblici
            list:
                batch_actions: ['delete']
                title: "Elenco commenti e segnalazioni"
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'image', base_path: "/uploads/photos/", label: 'Photo' }
                    - { property: 'createdAt', type: 'datetime' }
                    - { property: 'textComment', label: 'Commento'}
                    - state
                sort: ['createdAt', 'ASC']  
                filters: ['cantieri', 'state']
            edit:
                title: "Commento o segnalazione"
                fields:
                    - { property: 'cantieri' }
                    - { property: 'createdAt', type: datetime, type_options: { disabled: true } }
                    - 'author'
                    - { property: 'state' }
                    - { property: 'email', type: 'email' }
                    - textComment

      Province:
            class: App\Entity\Province
            list:
                title: "Elenco Province"

      RegoleFatturazione:
            class: App\Entity\RegoleFatturazione

