parameters:
    app.path.personale_images: /uploads/photos
    app.path.personale_documenti: /uploads/files/personale/documenti
    app.path.cantieri_documenti: /uploads/files/cantieri/documenti
    app.path.prodotti_images: /uploads/images
         # ...

services:
    # _defaults:
    #   bind:
    #       $photoDir: "%kernel.project_dir%/public/uploads/photos"  
    vendor\easycorp\easyadmin-bundle\src\Factory\ActionFactory: ~
    vendor\easycorp\easyadmin-bundle\src\Factory\ActionFactory: 
        class: App\EasyCorp\Bundle\EasyAdminBundle\Factory\ActionFactory