vich_uploader:
    db_driver: orm
    #
    mappings:
      personale_images:
          uri_prefix:         '%app.path.personale_images%'
          upload_destination: '%kernel.project_dir%/public%app.path.personale_images%'
          namer:
              service: Vich\UploaderBundle\Naming\HashNamer
              options: { algorithm: 'sha256', length: 40 }
        #  inject_on_load: false
        #  delete_on_update: true
        #  delete_on_remove: true
