name: app

type: php:7.4

runtime:
    extensions:
        - xsl
        - amqp
        - pdo_pgsql
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"


mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads/photos": { source: service, service: files, source_path: photos }
    "/public/uploads/images": { source: local, source_path: images }
    "/public/uploads/files/personale/import": { source: local, source_path: import }
    "/public/uploads/files/personale/cv": { source: local, source_path: cv }
    "/public/uploads/files/personale/documenti": { source: local, source_path: documenti }
    "/public/uploads/files/cantieri/documenti": { source: local, source_path: documenti }
    "/public/uploads/files/cantieri/import": { source: local, source_path: import }
    "/public/downloads/flowsalary": { source: local, source_path: flowsalary }
    "/public/downloads/excelExport": { source: local, source_path: excelExport }
    "/public/downloads/errorImport": { source: local, source_path: errorImport } 

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

workers:
    messages:
        commands:
            start: symfony console messenger:consume async -vv --time-limit=3600 --memory-limit=128M


relationships:
    database: "db:postgresql"
  

